name: CI main tests

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Shared unit tests
        run: |
          npm ci --prefix shared
          npm test --prefix shared

      - name: Backend unit tests
        run: |
          npm ci --prefix idle-backend
          npm test --prefix idle-backend

      - name: Frontend lint and unit tests
        run: |
          npm ci --prefix idle-react
          npm run --prefix idle-react lint
          npm test --prefix idle-react
